spring:
  datasource:
    url: jdbc:postgresql://${DB_URL}:${DB_PORT}/${DB_SCHEMA}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
server:
  servlet:
    session:
      timeout: 60m  # Session timeout
      cookie:
        name: JSESSIONID  # Name of the session cookie
        http-only: true  # Make cookie accessible only via HTTP (to improve security)
        secure: true  # Set to true if you're using HTTPS
        same-site: none
logging:
  level:
    org:
      springframework:
        security: DEBUG

