### GET all tasks
GET http://localhost:8080/task/all-task

### GET all task by user
GET http://localhost:8080/task/of-user/a08b7f5f-4179-44c5-9d72-d40c5cc30d89
### GET all task by project
GET http://localhost:8080/task/of-list/dff29c18-a939-413d-a309-00e90cd3decf

### GET task detail
GET http://localhost:8080/task/bdab46f0-4c39-42ef-a6bc-52ca5fb9e845

### POST task 1
POST http://localhost:8080/task/create-task
Content-Type: application/json

{
  "title": "task 1",
  "listId": "de37d624-5f33-400e-89a3-cde2beebe8b0"
}

### POST task 1.1
POST http://localhost:8080/task/create-task
Content-Type: application/json

{
  "title": "task 1.1",
  "description": "task 1 alt gorev",
  "listId": "de37d624-5f33-400e-89a3-cde2beebe8b0",
  "priority": "HIGH",
  "status": "TO_DO",
  "dueDate": "2024-07-24T15:30:00",
  "parentId": "bdab46f0-4c39-42ef-a6bc-52ca5fb9e845"
}

### POST task 2
POST http://localhost:8080/task/create-task
Content-Type: application/json

{
  "title": "task 2",
  "description": "task aciklama 2",
  "listId": "de37d624-5f33-400e-89a3-cde2beebe8b0",
  "priority": "LOW",

  "dueDate": "2024-07-30T15:30:00",
  "parentId": ""
}

### POST task 2.1
POST http://localhost:8080/task/create-task
Content-Type: application/json

{
  "title": "task 2.2",
  "description": "task 2 alt gorev 2",
  "listId": "de37d624-5f33-400e-89a3-cde2beebe8b0",
  "parentId": "2d2a98dd-54a1-49c3-a4f3-9e0a1bf74ab6",
  "dueDate": "2024-07-20T15:30:00"
}

### POST task 3
POST http://localhost:8080/task/create-task
Content-Type: application/json

{
  "title": "task 3",
  "listId": "de37d624-5f33-400e-89a3-cde2beebe8b0"
}

### PUT task 1
PUT http://localhost:8080/task/edit/
Content-Type: application/json

{
  "title": "task 1",
  "description": "aciklama 1",
  "listId": "ba03feb5-3719-48cc-ac81-bf5be27a0816",
  "priority": "HIGH",
  "startedAt": "2024-07-17T15:30:00"
}

### DELETE task 1
DELETE http://localhost:8080/task/delete/
